public class Options extends javax.swing.JFrame {

    /**
     * Creates new form Options
     */
    public Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addBook = new javax.swing.JButton();
        deleteBook = new javax.swing.JButton();
        displayInfo = new javax.swing.JButton();
        listBooks = new javax.swing.JButton();
        displayFinishedBooks = new javax.swing.JButton();
        displayImage = new javax.swing.JButton();
        ListInOrderToRatings = new javax.swing.JButton();
        listByTitle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(jLabel1.getFont().deriveFont((float)18));
        jLabel1.setText("Options");

        addBook.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addBook.setText("Add Book");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });

        deleteBook.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteBook.setText("Delete Book");
        deleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookActionPerformed(evt);
            }
        });

        displayInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        displayInfo.setText("Display Book Information");
        displayInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayInfoActionPerformed(evt);
            }
        });

        listBooks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listBooks.setText("List The Books by Title & Description");
        listBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBooksActionPerformed(evt);
            }
        });

        displayFinishedBooks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        displayFinishedBooks.setText("Display Finished Books  ");
        displayFinishedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayFinishedBooksActionPerformed(evt);
            }
        });

        displayImage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        displayImage.setText("Display Image");
        displayImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayImageActionPerformed(evt);
            }
        });

        ListInOrderToRatings.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ListInOrderToRatings.setText("List The Books in order to Ratings");
        ListInOrderToRatings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListInOrderToRatingsActionPerformed(evt);
            }
        });

        listByTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listByTitle.setText("List The Books by Title");
        listByTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listByTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(displayFinishedBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displayImage, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(displayInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listByTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ListInOrderToRatings, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBook, deleteBook, displayFinishedBooks, displayImage, displayInfo, listBooks});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(addBook)
                .addGap(18, 18, 18)
                .addComponent(deleteBook)
                .addGap(18, 18, 18)
                .addComponent(displayInfo)
                .addGap(18, 18, 18)
                .addComponent(displayImage)
                .addGap(18, 18, 18)
                .addComponent(listBooks)
                .addGap(18, 18, 18)
                .addComponent(listByTitle)
                .addGap(18, 18, 18)
                .addComponent(ListInOrderToRatings)
                .addGap(18, 18, 18)
                .addComponent(displayFinishedBooks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addBook, deleteBook, displayFinishedBooks, displayImage, displayInfo, listBooks});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //In this frame ,the user selects an action and from the selected action,these following actionPerformed functions make the selected frame visible and make the options frame invisible.
    //Users can be turn back to option frame when they want to,because each frame there is an return options button.
    
    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        AddBook addbook=new AddBook();
        this.setVisible(false);
        addbook.setVisible(true);
    }//GEN-LAST:event_addBookActionPerformed

    private void displayFinishedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayFinishedBooksActionPerformed
        FinishedBooks finishedBooks=new FinishedBooks();
        this.setVisible(false);
        finishedBooks.setVisible(true);
    }//GEN-LAST:event_displayFinishedBooksActionPerformed

    private void deleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookActionPerformed
        DeleteBook deleteBook =new DeleteBook();
        this.setVisible(false);
        deleteBook.setVisible(true);
    }//GEN-LAST:event_deleteBookActionPerformed

    private void displayInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayInfoActionPerformed
        DisplayInformation display=new DisplayInformation();
        this.setVisible(false);
        display.setVisible(true);
    }//GEN-LAST:event_displayInfoActionPerformed

    private void listBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBooksActionPerformed
      ListbyTitleAndDescription list=new ListbyTitleAndDescription();
      this.setVisible(false);
      list.setVisible(true);
    }//GEN-LAST:event_listBooksActionPerformed

    private void displayImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayImageActionPerformed
        DisplayImages dispImg =new DisplayImages();
        this.setVisible(false);
        dispImg.setVisible(true);
    }//GEN-LAST:event_displayImageActionPerformed

    private void ListInOrderToRatingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListInOrderToRatingsActionPerformed
       ListbyRatings list =new ListbyRatings();
       this.setVisible(false);
       list.setVisible(true);
    }//GEN-LAST:event_ListInOrderToRatingsActionPerformed

    private void listByTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listByTitleActionPerformed
        ListbyTitle list=new ListbyTitle();
        this.setVisible(false);
        list.setVisible(true);
    }//GEN-LAST:event_listByTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Options().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListInOrderToRatings;
    private javax.swing.JButton addBook;
    private javax.swing.JButton deleteBook;
    private javax.swing.JButton displayFinishedBooks;
    private javax.swing.JButton displayImage;
    private javax.swing.JButton displayInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listBooks;
    private javax.swing.JButton listByTitle;
    // End of variables declaration//GEN-END:variables
}
